
# 📋 Extended Institutional Stock Watchlist
# Contains all requested symbols for market-wide scanning

EXTENDED_STOCKS_LIST = [
    "INDIANB", "UNIONBANK", "ADANIPORTS", "AMBER", "CUMMINSIND", "POLICYBZR", "AXISBANK", 
    "HDFCLIFE", "PNB", "BHARATFORG", "SBILIFE", "ICICIPRULI", "CHOLAFIN", "MFSL", 
    "CANBK", "KOTAKBANK", "POWERINDIA", "TATACONSUM", "BANKBARODA", "HDFCBANK", 
    "LUPIN", "ICICIGI", "IOC", "EICHERMOT", "HINDUNILVR", "ADANIENT", "NESTLEIND", 
    "BANKINDIA", "BPCL", "HINDPETRO", "TVSMOTOR", "SBIN", "MAXHEALTH", "DRREDDY", 
    "ADANIGREEN", "FORTIS", "ASHOKLEY", "SIEMENS", "MUTHOOTFIN", "KFINTECH", 
    "POWERGRID", "SONACOMS", "CONCOR", "M&M", "TORNTPHARM", "DALBHARAT", "SHRIRAMFIN", 
    "HDFCAMC", "GODREJCP", "JSWSTEEL", "GRASIM", "HINDZINC", "BHARTIARTL", "SHREECEM", 
    "UNITDSPR", "PAGEIND", "BAJAJHLDNG", "ZYDUSLIFE", "DELHIVERY", "LICI", 
    "TORNTPOWER", "ICICIBANK", "LTF", "BAJFINANCE", "GMRAIRPORT", "MARICO", "MARUTI", 
    "PIDILITIND", "CGPOWER", "PFC", "BAJAJ-AUTO", "AUROPHARMA", "APOLLOHOSP", "KEI", 
    "ABCAPITAL", "TITAN", "PAYTM", "HEROMOTOCO", "PIIND", "PHOENIXLTD", "TMPV", 
    "360ONE", "LT", "PRESTIGE", "NTPC", "PPLPHARMA", "BANDHANBNK", "RELIANCE", 
    "TATAPOWER", "VBL", "CDSL", "MANAPPURAM", "AMBUJACEM", "NYKAA", "MANKIND", 
    "LODHA", "SBICARD", "ALKEM", "ULTRACEMCO", "SUPREMEIND", "CAMS", "COLPAL", 
    "ASIANPAINT", "MCX", "BLUESTARCO", "KALYANKJIL", "ADANIENSOL", "BOSCHLTD", 
    "DIVISLAB", "APLAPOLLO", "DABUR", "POLYCAB", "CROMPTON", "RVNL", "PETRONET", 
    "LICHSGFIN", "SUNPHARMA", "VOLTAS", "BIOCON", "ASTRAL", "VEDL", "NBCC", 
    "BHEL", "JINDALSTEL", "HUDCO", "FEDERALBNK", "INDHOTEL", "SOLARINDS", 
    "GODREJPROP", "BAJAJFINSV", "NATIONALUM", "IRFC", "HAVELLS", "INDIGO", 
    "EXIDEIND", "IEX", "ANGELONE", "WAAREEENER", "RECLTD", "BRITANNIA", "JUBLFOOD", 
    "COALINDIA", "TATASTEEL", "PNBHOUSING", "DLF", "LAURUSLABS", "ITC", "UNOMINDA", 
    "YESBANK", "DMART", "BSE", "SUZLON", "MOTHERSON", "GLENMARK", "PREMIERENE", 
    "PGEL", "NHPC", "PATANJALI", "TATATECH", "SRF", "JSWENERGY", "BEL", "HINDALCO", 
    "IRCTC", "SAIL", "TRENT", "JIOFIN", "IREDA", "INDUSTOWER", "GAIL", "NAUKRI", 
    "TCS", "OFSS", "ABB", "OBEROIRLTY", "CIPLA", "SAMMAANCAP", "PERSISTENT", 
    "HCLTECH", "SYNGENE", "MAZDOCK", "INDUSINDBK", "ETERNAL", "NMDC", "KAYNES", 
    "NUVAMA", "OIL", "SWIGGY", "TECHM", "TIINDIA", "TATAELXSI", "RBLBANK", 
    "IDEA", "KPITTECH", "LTIM", "ONGC", "INFY", "INOXWIND", "DIXON", "MPHASIS", 
    "WIPRO", "HAL", "BDL", "COFORGE", "AUBANK", "UPL", "IDFCFIRSTB"
]
